import type {
  User,
  Tenant,
  Item,
  Order,
  ProductionLog,
  Employee,
  ActiveTask,
  AppNotification,
  StockEntry,
  StockMovement,
  NestTask,
  Customer,
  Sector,
  ProductFlow,
  ProductionBatch,
  ProductionAgenda,
  Carga,
  ExpeditionRoute,
  ProductionSchedule,
  SystemSettings,
  ProductAttribute,
} from "./types";

export const isDemoModeEnabled = () => {
  if (typeof window === "undefined") return false;
  const value = new URLSearchParams(window.location.search).get("demo");
  return value === "1" || value === "true";
};

export const DEMO_TENANT_ID = "demo-fabrica";

export const DEMO_USER: User = {
  id: "demo-raul",
  name: "Raul (DEMO)",
  role: "ADMIN",
  password: "demo",
  tenantId: DEMO_TENANT_ID,
};

export const DEMO_TENANT: Tenant = {
  id: DEMO_TENANT_ID,
  name: "Fábrica Aurora • Ambiente DEMO",
  systemName: "Apontador de Produção",
  primaryColor: "#00B14F",
  monthlyBillingGoal: 320000,
  machines: [
    "Laser Aurora",
    "Prensa Eduardo",
    "Prensa Rafael",
    "Torno Willian",
    "Torno Henrique",
    "Injetora",
  ],
  exigirQualidadeNaEmbalagem: true,
};

type DemoRecord<T> = T & { tenantId: string };

const timestamp = (value: string) => new Date(value).getTime();

export const DEMO_ITEMS: Array<DemoRecord<Item>> = [
  {
    id: 9001,
    code: "AUR-PE-040",
    name: "Suporte Atlas 40",
    notes: "Peça metálica de apoio para a linha Atlas.",
    unit: "UN",
    type: "PECA",
    basePrice: 18.5,
    productiveCost: 7.8,
    productionPoints: 0.9,
    standardCycles: { 1: 14, 2: 26, 3: 18 },
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9002,
    code: "AUR-ME-120",
    name: "Mesa Nexo 120",
    notes: "Produto acabado com estrutura modular.",
    unit: "UN",
    type: "PRODUTO",
    basePrice: 489,
    productiveCost: 214,
    productionPoints: 2.4,
    components: [{ itemId: 9001, quantity: 2 }],
    standardCycles: { 2: 58, 3: 42, 4: 20 },
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9003,
    code: "AUR-ES-005",
    name: "Estante Lume 5P",
    notes: "Estante de cinco prateleiras para showroom.",
    unit: "UN",
    type: "PRODUTO",
    basePrice: 798,
    productiveCost: 348,
    productionPoints: 3.6,
    components: [{ itemId: 9001, quantity: 4 }],
    standardCycles: { 2: 86, 3: 55, 4: 24 },
    requiresLaserCut: true,
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9004,
    code: "AUR-TR-090",
    name: "Trilho Prisma 90",
    notes: "Componente de acabamento da linha Prisma.",
    unit: "UN",
    type: "PECA",
    basePrice: 26.9,
    productiveCost: 11.4,
    productionPoints: 1.1,
    standardCycles: { 1: 18, 2: 32, 3: 20 },
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9005,
    code: "AUR-BC-180",
    name: "Balcão Vértice 180",
    notes: "Balcão expositor com acabamento fosco.",
    unit: "UN",
    type: "PRODUTO",
    basePrice: 1120,
    productiveCost: 520,
    productionPoints: 4.2,
    components: [
      { itemId: 9001, quantity: 4 },
      { itemId: 9004, quantity: 2 },
    ],
    standardCycles: { 2: 105, 3: 70, 4: 30 },
    requiresLaserCut: true,
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9006,
    code: "AUR-PA-090",
    name: "Painel Prisma 90",
    notes: "Painel modular para exposição de produtos.",
    unit: "UN",
    type: "PRODUTO",
    basePrice: 640,
    productiveCost: 286,
    productionPoints: 2.9,
    components: [{ itemId: 9004, quantity: 2 }],
    standardCycles: { 2: 62, 3: 44, 4: 18 },
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_CUSTOMERS: Array<DemoRecord<Customer>> = [
  {
    id: 9101,
    name: "Casa Horizonte DEMO",
    tradeName: "Casa Horizonte",
    email: "compras@casa-horizonte.example.invalid",
    phone: "(00) 00000-9101",
    address: "Rua das Acácias, 120",
    neighborhood: "Centro",
    city: "Cidade Modelo",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9102,
    name: "Studio Nexo DEMO",
    tradeName: "Studio Nexo",
    email: "pedidos@studio-nexo.example.invalid",
    phone: "(00) 00000-9102",
    address: "Avenida Central, 450",
    neighborhood: "Jardins",
    city: "Cidade Modelo",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9103,
    name: "Constrular Vértice DEMO",
    tradeName: "Constrular Vértice",
    email: "compras@constrular-vertice.example.invalid",
    phone: "(00) 00000-9103",
    address: "Rua do Comércio, 880",
    neighborhood: "Industrial",
    city: "Cidade Modelo",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9104,
    name: "Showroom Lume DEMO",
    tradeName: "Showroom Lume",
    email: "operacao@showroom-lume.example.invalid",
    phone: "(00) 00000-9104",
    address: "Alameda do Design, 32",
    neighborhood: "Vila Nova",
    city: "Cidade Modelo",
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_ORDERS: Array<DemoRecord<Order>> = [
  {
    id: 9201,
    orderCode: "D-2601",
    itemId: 9002,
    color: "Grafite",
    size: "120 cm",
    variation: "Pé reto",
    customerName: "Casa Horizonte DEMO",
    representativeName: "Camila Souza (DEMO)",
    representativeId: "demo-camila",
    totalQuantity: 24,
    packedQuantity: 0,
    producedQuantity: 0,
    paintedQuantity: 0,
    cutQuantity: 24,
    invoicedQuantity: 0,
    isActive: true,
    createdAt: timestamp("2026-09-17T08:20:00-03:00"),
    deliveryDate: "2026-09-25",
    status: "PENDENTE",
    isUrgent: true,
    isProgramacao: true,
    unitPrice: 489,
    unit: "UN",
    paymentCondition: "28 dias",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9202,
    orderCode: "D-2602",
    itemId: 9003,
    color: "Preto Fosco",
    size: "180 cm",
    variation: "5 prateleiras",
    customerName: "Studio Nexo DEMO",
    representativeName: "Diego Martins (DEMO)",
    representativeId: "demo-diego",
    totalQuantity: 18,
    packedQuantity: 0,
    producedQuantity: 12,
    paintedQuantity: 0,
    cutQuantity: 18,
    invoicedQuantity: 0,
    isActive: true,
    createdAt: timestamp("2026-09-16T09:10:00-03:00"),
    deliveryDate: "2026-09-27",
    status: "EM_PRODUCAO",
    unitPrice: 798,
    unit: "UN",
    paymentCondition: "21 dias",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9203,
    orderCode: "D-2603",
    itemId: 9005,
    color: "Branco",
    size: "180 cm",
    variation: "Fosco",
    customerName: "Constrular Vértice DEMO",
    representativeName: "Camila Souza (DEMO)",
    representativeId: "demo-camila",
    totalQuantity: 12,
    packedQuantity: 0,
    producedQuantity: 12,
    paintedQuantity: 8,
    cutQuantity: 12,
    invoicedQuantity: 0,
    isActive: true,
    createdAt: timestamp("2026-09-15T10:35:00-03:00"),
    deliveryDate: "2026-09-23",
    status: "EM_PINTURA",
    isProgramacao: true,
    unitPrice: 1120,
    unit: "UN",
    paymentCondition: "28 dias",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9204,
    orderCode: "D-2604",
    itemId: 9006,
    color: "Areia",
    size: "90 cm",
    variation: "Modular",
    customerName: "Showroom Lume DEMO",
    representativeName: "Diego Martins (DEMO)",
    representativeId: "demo-diego",
    totalQuantity: 30,
    packedQuantity: 18,
    producedQuantity: 30,
    paintedQuantity: 30,
    cutQuantity: 30,
    invoicedQuantity: 0,
    isActive: true,
    createdAt: timestamp("2026-09-12T13:00:00-03:00"),
    deliveryDate: "2026-09-22",
    status: "EMBALANDO",
    unitPrice: 640,
    unit: "UN",
    paymentCondition: "14 dias",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9205,
    orderCode: "D-2605",
    itemId: 9002,
    color: "Cinza",
    size: "120 cm",
    variation: "Pé reto",
    customerName: "Casa Horizonte DEMO",
    representativeName: "Camila Souza (DEMO)",
    representativeId: "demo-camila",
    totalQuantity: 20,
    packedQuantity: 20,
    producedQuantity: 20,
    paintedQuantity: 20,
    cutQuantity: 20,
    invoicedQuantity: 20,
    isActive: true,
    createdAt: timestamp("2026-09-10T08:45:00-03:00"),
    deliveryDate: "2026-09-20",
    status: "FATURADO",
    unitPrice: 489,
    unit: "UN",
    paymentCondition: "28 dias",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9206,
    orderCode: "D-2606",
    itemId: 9001,
    color: "Zincado",
    size: "40 mm",
    variation: "Padrão",
    customerName: "Constrular Vértice DEMO",
    representativeName: "Ana Lima (DEMO)",
    representativeId: "demo-ana",
    totalQuantity: 16,
    packedQuantity: 0,
    producedQuantity: 0,
    paintedQuantity: 0,
    cutQuantity: 16,
    invoicedQuantity: 0,
    isActive: true,
    createdAt: timestamp("2026-09-18T11:20:00-03:00"),
    deliveryDate: "2026-09-29",
    status: "CORTADO",
    unitPrice: 18.5,
    unit: "UN",
    paymentCondition: "14 dias",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9207,
    orderCode: "D-2607",
    itemId: 9006,
    color: "Verde Oliva",
    size: "90 cm",
    variation: "Modular",
    customerName: "Studio Nexo DEMO",
    representativeName: "Ana Lima (DEMO)",
    representativeId: "demo-ana",
    totalQuantity: 10,
    packedQuantity: 0,
    producedQuantity: 10,
    paintedQuantity: 10,
    cutQuantity: 10,
    invoicedQuantity: 0,
    isActive: true,
    createdAt: timestamp("2026-09-14T14:15:00-03:00"),
    deliveryDate: "2026-09-24",
    status: "PRODUZIDO",
    unitPrice: 640,
    unit: "UN",
    paymentCondition: "21 dias",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9208,
    orderCode: "D-2608",
    itemId: 9005,
    color: "Terracota",
    size: "180 cm",
    variation: "Fosco",
    customerName: "Showroom Lume DEMO",
    representativeName: "Diego Martins (DEMO)",
    representativeId: "demo-diego",
    totalQuantity: 8,
    packedQuantity: 0,
    producedQuantity: 0,
    paintedQuantity: 0,
    cutQuantity: 0,
    invoicedQuantity: 0,
    isActive: true,
    createdAt: timestamp("2026-09-09T15:30:00-03:00"),
    deliveryDate: "2026-09-21",
    status: "PENDENTE",
    isUrgent: true,
    unitPrice: 1120,
    unit: "UN",
    paymentCondition: "28 dias",
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_LOGS: Array<DemoRecord<ProductionLog>> = [
  {
    id: 9301,
    orderId: 9202,
    itemId: 9003,
    operatorId: "demo-prod-1",
    type: "PRODUCAO",
    processName: "Montagem estrutural",
    quantityProcessed: 12,
    timestamp: timestamp("2026-09-20T16:40:00-03:00"),
    durationMillis: 15400000,
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9302,
    orderId: 9203,
    itemId: 9005,
    operatorId: "demo-solda-1",
    type: "SOLDA" as ProductionLog["type"],
    processName: "Solda de estrutura",
    quantityProcessed: 12,
    timestamp: timestamp("2026-09-20T15:10:00-03:00"),
    durationMillis: 12800000,
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9303,
    orderId: 9203,
    itemId: 9005,
    operatorId: "demo-pintura-1",
    type: "PINTURA",
    processName: "Pintura eletrostática",
    quantityPainted: 8,
    paintedColor: "Branco",
    timestamp: timestamp("2026-09-21T08:30:00-03:00"),
    durationMillis: 9700000,
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9304,
    orderId: 9204,
    itemId: 9006,
    operatorId: "demo-emb-1",
    type: "EMBALAGEM",
    processName: "Embalagem final",
    quantityPacked: 18,
    timestamp: timestamp("2026-09-21T09:20:00-03:00"),
    durationMillis: 6200000,
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9305,
    orderId: 9205,
    itemId: 9002,
    operatorId: "demo-exp-1",
    type: "FATURAMENTO",
    processName: "Expedição",
    quantityInvoiced: 20,
    timestamp: timestamp("2026-09-20T11:05:00-03:00"),
    durationMillis: 1800000,
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9306,
    orderId: 9207,
    itemId: 9006,
    operatorId: "demo-pintura-1",
    type: "PINTURA",
    processName: "Pintura eletrostática",
    quantityPainted: 10,
    paintedColor: "Verde Oliva",
    timestamp: timestamp("2026-09-20T13:50:00-03:00"),
    durationMillis: 7400000,
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_SECTORS: Array<DemoRecord<Sector>> = [
  { id: 1, name: "Corte Laser", department: "Produção", active: true, code: "LASER", dailyCapacity: 420, tenantId: DEMO_TENANT_ID },
  { id: 2, name: "Produção", department: "Fábrica", active: true, code: "PROD", dailyCapacity: 260, tenantId: DEMO_TENANT_ID },
  { id: 3, name: "Pintura", department: "Acabamento", active: true, code: "PINT", dailyCapacity: 180, tenantId: DEMO_TENANT_ID },
  { id: 4, name: "Embalagem", department: "Expedição", active: true, code: "EMB", dailyCapacity: 220, tenantId: DEMO_TENANT_ID },
  { id: 5, name: "Montagem", department: "Fábrica", active: true, code: "MONT", dailyCapacity: 240, tenantId: DEMO_TENANT_ID },
  { id: 6, name: "Expedição", department: "Logística", active: true, code: "EXP", dailyCapacity: 160, tenantId: DEMO_TENANT_ID },
];

export const DEMO_EMPLOYEES: Array<DemoRecord<Employee>> = [
  { id: "demo-prod-1", name: "Lucas Andrade (DEMO)", sectorId: 2, isActive: true, tenantId: DEMO_TENANT_ID },
  { id: "demo-solda-1", name: "Marina Costa (DEMO)", sectorId: 2, isActive: true, tenantId: DEMO_TENANT_ID },
  { id: "demo-pintura-1", name: "Rafael Nunes (DEMO)", sectorId: 3, isActive: true, tenantId: DEMO_TENANT_ID },
  { id: "demo-emb-1", name: "Bianca Alves (DEMO)", sectorId: 4, isActive: true, tenantId: DEMO_TENANT_ID },
  { id: "demo-exp-1", name: "Caio Mendes (DEMO)", sectorId: 6, isActive: true, tenantId: DEMO_TENANT_ID },
  { id: "demo-pcp-1", name: "Joana Ribeiro (DEMO)", sectorId: 5, isActive: true, tenantId: DEMO_TENANT_ID },
];

export const DEMO_STOCKS: Array<DemoRecord<StockEntry>> = [
  { id: "9001|Grafite|40 mm|Padrão|INTERMEDIARIO", itemId: 9001, color: "Grafite", size: "40 mm", variation: "Padrão", quantity: 184, reservedQuantity: 36, stage: "INTERMEDIARIO", tenantId: DEMO_TENANT_ID },
  { id: "9001|Zincado|40 mm|Padrão|INTERMEDIARIO", itemId: 9001, color: "Zincado", size: "40 mm", variation: "Padrão", quantity: 96, reservedQuantity: 16, stage: "INTERMEDIARIO", tenantId: DEMO_TENANT_ID },
  { id: "9002|Grafite|120 cm|Pé reto|ACABADO", itemId: 9002, color: "Grafite", size: "120 cm", variation: "Pé reto", quantity: 42, reservedQuantity: 24, stage: "ACABADO", tenantId: DEMO_TENANT_ID },
  { id: "9003|Preto Fosco|180 cm|5 prateleiras|ACABADO", itemId: 9003, color: "Preto Fosco", size: "180 cm", variation: "5 prateleiras", quantity: 10, reservedQuantity: 6, stage: "ACABADO", tenantId: DEMO_TENANT_ID },
  { id: "9006|Verde Oliva|90 cm|Modular|ACABADO", itemId: 9006, color: "Verde Oliva", size: "90 cm", variation: "Modular", quantity: 14, reservedQuantity: 10, stage: "ACABADO", tenantId: DEMO_TENANT_ID },
];

export const DEMO_STOCK_MOVEMENTS: Array<DemoRecord<StockMovement>> = [
  { id: "demo-mov-1", itemId: 9001, color: "Grafite", size: "40 mm", variation: "Padrão", quantity: 96, type: "ENTRADA", description: "Entrada de produção • Lote DEMO-07", timestamp: timestamp("2026-09-21T08:05:00-03:00"), tenantId: DEMO_TENANT_ID },
  { id: "demo-mov-2", itemId: 9002, color: "Grafite", size: "120 cm", variation: "Pé reto", quantity: 24, type: "SAIDA", description: "Reserva para pedido D-2601", timestamp: timestamp("2026-09-21T08:20:00-03:00"), tenantId: DEMO_TENANT_ID },
  { id: "demo-mov-3", itemId: 9003, color: "Preto Fosco", size: "180 cm", variation: "5 prateleiras", quantity: 18, type: "ENTRADA", description: "Produção concluída • Lote DEMO-06", timestamp: timestamp("2026-09-20T16:40:00-03:00"), tenantId: DEMO_TENANT_ID },
  { id: "demo-mov-4", itemId: 9006, color: "Verde Oliva", size: "90 cm", variation: "Modular", quantity: 10, type: "ENTRADA", description: "Pintura finalizada • Pedido D-2607", timestamp: timestamp("2026-09-20T13:50:00-03:00"), tenantId: DEMO_TENANT_ID },
];

export const DEMO_ACTIVE_PACKS: Array<DemoRecord<ActiveTask>> = [
  {
    id: 9401,
    itemId: 9003,
    color: "Preto Fosco",
    size: "180 cm",
    variation: "5 prateleiras",
    operatorId: "demo-prod-1",
    startTime: timestamp("2026-09-21T07:40:00-03:00"),
    type: "PRODUCAO",
    processName: "Montagem estrutural",
    partialQuantity: 12,
    sectorId: 2,
    sectorName: "Produção",
    orderCode: "D-2602",
    customerName: "Studio Nexo DEMO",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9402,
    itemId: 9005,
    color: "Branco",
    size: "180 cm",
    variation: "Fosco",
    operatorId: "demo-solda-1",
    startTime: timestamp("2026-09-21T08:10:00-03:00"),
    type: "PINTURA",
    processName: "Pintura eletrostática",
    partialQuantity: 8,
    sectorId: 3,
    sectorName: "Pintura",
    orderCode: "D-2603",
    customerName: "Constrular Vértice DEMO",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9403,
    itemId: 9006,
    color: "Areia",
    size: "90 cm",
    variation: "Modular",
    operatorId: "demo-emb-1",
    startTime: timestamp("2026-09-21T09:00:00-03:00"),
    type: "EMBALAGEM",
    processName: "Embalagem final",
    partialQuantity: 18,
    sectorId: 4,
    sectorName: "Embalagem",
    orderCode: "D-2604",
    customerName: "Showroom Lume DEMO",
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_NEST_TASKS: Array<DemoRecord<NestTask>> = [
  {
    id: 9501,
    nestName: "Nesting DEMO • 21/09",
    partName: "Suporte Atlas 40",
    size: "40 mm",
    totalQuantity: 240,
    cutQuantity: 184,
    status: "EM_CORTE",
    isActive: true,
    createdAt: timestamp("2026-09-21T06:50:00-03:00"),
    sequence: 1,
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9502,
    nestName: "Nesting DEMO • 20/09",
    partName: "Trilho Prisma 90",
    size: "90 cm",
    totalQuantity: 120,
    cutQuantity: 120,
    status: "CORTADO",
    isActive: true,
    createdAt: timestamp("2026-09-20T07:20:00-03:00"),
    sequence: 2,
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_PRODUCTION_BATCHES: Array<DemoRecord<ProductionBatch>> = [
  {
    id: 9601,
    name: "Lote DEMO • Linha Prisma",
    sectorId: 2,
    orderIds: [9202, 9203],
    status: "EM_PRODUCAO",
    createdAt: timestamp("2026-09-20T07:00:00-03:00"),
    deadline: "2026-09-23",
    rawMaterial: "Chapa galvanizada 1,20 mm",
    generatedPiece: "Estrutura Prisma",
    notes: "Lote de demonstração para acompanhamento do PCP.",
    assignedOperatorIds: ["demo-prod-1", "demo-solda-1"],
    checkedOrderIds: [9202],
    liberatedOrderIds: [9202, 9203],
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9602,
    name: "Lote DEMO • Expedição 22/09",
    sectorId: 4,
    orderIds: [9204, 9207],
    status: "PENDENTE",
    createdAt: timestamp("2026-09-21T07:30:00-03:00"),
    deadline: "2026-09-22",
    notes: "Separação priorizada para a próxima carga.",
    assignedOperatorIds: ["demo-emb-1"],
    liberatedOrderIds: [9204, 9207],
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9603,
    name: "Lote DEMO • Corte Laser",
    sectorId: 1,
    orderIds: [9201, 9206],
    status: "CONCLUIDO",
    createdAt: timestamp("2026-09-19T07:10:00-03:00"),
    deadline: "2026-09-21",
    notes: "Corte liberado para produção.",
    assignedOperatorIds: ["demo-pcp-1"],
    checkedOrderIds: [9201, 9206],
    liberatedOrderIds: [9201, 9206],
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_PRODUCTION_AGENDAS: Array<DemoRecord<ProductionAgenda>> = [
  { id: 9701, orderId: 9201, batchId: 9601, sectorId: 2, estimatedDate: "2026-09-22", tenantId: DEMO_TENANT_ID },
  { id: 9702, orderId: 9202, batchId: 9601, sectorId: 2, estimatedDate: "2026-09-22", tenantId: DEMO_TENANT_ID },
  { id: 9703, orderId: 9203, batchId: 9601, sectorId: 3, estimatedDate: "2026-09-22", tenantId: DEMO_TENANT_ID },
  { id: 9704, orderId: 9204, batchId: 9602, sectorId: 4, estimatedDate: "2026-09-21", tenantId: DEMO_TENANT_ID },
  { id: 9705, orderId: 9208, sectorId: 1, estimatedDate: "2026-09-23", tenantId: DEMO_TENANT_ID },
];

export const DEMO_PRODUCT_FLOWS: Array<DemoRecord<ProductFlow>> = [
  { id: 9801, itemId: 9002, sectorIds: [2, 3, 4], sectorTimes: { "2": 58, "3": 42, "4": 20 }, tenantId: DEMO_TENANT_ID },
  { id: 9802, itemId: 9003, sectorIds: [1, 2, 3, 4], sectorTimes: { "1": 18, "2": 86, "3": 55, "4": 24 }, tenantId: DEMO_TENANT_ID },
  { id: 9803, itemId: 9005, sectorIds: [1, 2, 3, 4], sectorTimes: { "1": 22, "2": 105, "3": 70, "4": 30 }, tenantId: DEMO_TENANT_ID },
];

export const DEMO_ATTRIBUTES: Array<DemoRecord<ProductAttribute>> = [
  { id: 9901, type: "COLOR", value: "Grafite", code: "13", tenantId: DEMO_TENANT_ID },
  { id: 9902, type: "COLOR", value: "Preto Fosco", code: "3", tenantId: DEMO_TENANT_ID },
  { id: 9903, type: "COLOR", value: "Branco", code: "10", tenantId: DEMO_TENANT_ID },
  { id: 9904, type: "COLOR", value: "Verde Oliva", code: "16", tenantId: DEMO_TENANT_ID },
  { id: 9905, type: "SIZE", value: "90 cm", tenantId: DEMO_TENANT_ID },
  { id: 9906, type: "SIZE", value: "120 cm", tenantId: DEMO_TENANT_ID },
  { id: 9907, type: "SIZE", value: "180 cm", tenantId: DEMO_TENANT_ID },
];

export const DEMO_EXPEDITION_ROUTES: Array<DemoRecord<ExpeditionRoute>> = [
  {
    id: "demo-rota-1",
    name: "Rota Centro & Zona Sul",
    weekday: 1,
    shift: "MANHA",
    cutoffTime: "16:00",
    customerIds: [9101, 9102],
    active: true,
    createdAt: timestamp("2026-09-01T08:00:00-03:00"),
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: "demo-rota-2",
    name: "Rota Industrial",
    weekday: 2,
    shift: "TARDE",
    cutoffTime: "11:00",
    customerIds: [9103, 9104],
    active: true,
    createdAt: timestamp("2026-09-01T08:10:00-03:00"),
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_CARGAS: Array<DemoRecord<Carga>> = [
  {
    id: "demo-carga-1",
    name: "Carga DEMO • Terça-feira",
    dayOfWeek: "Terça-feira",
    routeId: "demo-rota-1",
    routeName: "Rota Centro & Zona Sul",
    shift: "MANHA",
    scheduledDate: "2026-09-22",
    orderIds: [9204, 9207],
    orderQuantities: { 9204: 18, 9207: 10 },
    separatedQuantities: { 9204: 12, 9207: 10 },
    stagingLocation: "Doca DEMO 01",
    status: "EM_SEPARACAO",
    createdAt: timestamp("2026-09-21T07:45:00-03:00"),
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: "demo-carga-2",
    name: "Carga DEMO • Quarta-feira",
    dayOfWeek: "Quarta-feira",
    routeId: "demo-rota-2",
    routeName: "Rota Industrial",
    shift: "TARDE",
    scheduledDate: "2026-09-23",
    orderIds: [9203, 9205],
    orderQuantities: { 9203: 12, 9205: 20 },
    separatedQuantities: { 9203: 12, 9205: 20 },
    stagingLocation: "Doca DEMO 02",
    status: "PRONTA",
    createdAt: timestamp("2026-09-20T10:15:00-03:00"),
    releasedAt: timestamp("2026-09-21T09:00:00-03:00"),
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_SCHEDULES: Array<DemoRecord<ProductionSchedule>> = [
  {
    id: "global",
    workingDays: [1, 2, 3, 4, 5],
    startHour: "07:00",
    endHour: "17:00",
    lunchStart: "11:30",
    lunchEnd: "12:30",
    coffeeBreaks: [{ start: "09:30", end: "09:45" }, { start: "15:00", end: "15:15" }],
    holidays: [],
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_SYSTEM_SETTINGS: Array<DemoRecord<SystemSettings>> = [
  {
    id: "default",
    companyName: "Fábrica Aurora • Ambiente DEMO",
    systemName: "Apontador de Produção",
    primaryColor: "#00B14F",
    monthlyBillingGoal: 320000,
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_NOTIFICATIONS: Array<DemoRecord<AppNotification>> = [
  {
    id: 9911,
    title: "Lote liberado",
    message: "O lote DEMO • Linha Prisma foi liberado para Produção.",
    read: false,
    createdAt: timestamp("2026-09-21T09:05:00-03:00"),
    type: "lote",
    severity: "medium",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9912,
    title: "Carga pronta",
    message: "A carga DEMO • Quarta-feira está pronta para conferência.",
    read: false,
    createdAt: timestamp("2026-09-21T08:55:00-03:00"),
    type: "carga",
    severity: "low",
    tenantId: DEMO_TENANT_ID,
  },
  {
    id: 9913,
    title: "Pedido urgente",
    message: "O pedido D-2608 foi marcado como urgente pela demonstração.",
    read: true,
    createdAt: timestamp("2026-09-20T16:20:00-03:00"),
    type: "novo_pedido",
    severity: "high",
    orderId: 9208,
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_DATABASE = {
  tenant: DEMO_TENANT,
  tenants: [DEMO_TENANT],
  user: DEMO_USER,
  users: [DEMO_USER],
  items: DEMO_ITEMS,
  orders: DEMO_ORDERS,
  logs: DEMO_LOGS,
  attributes: DEMO_ATTRIBUTES,
  activePacks: DEMO_ACTIVE_PACKS,
  nestTasks: DEMO_NEST_TASKS,
  notifications: DEMO_NOTIFICATIONS,
  stocks: DEMO_STOCKS,
  stockMovements: DEMO_STOCK_MOVEMENTS,
  employees: DEMO_EMPLOYEES,
  epiDistributions: [],
  uniforms: [],
  uniformDistributions: [],
  customers: DEMO_CUSTOMERS,
  sectors: DEMO_SECTORS,
  productFlows: DEMO_PRODUCT_FLOWS,
  flows: [],
  rejectionReasons: [],
  productionSteps: [],
  productionBatches: DEMO_PRODUCTION_BATCHES,
  productionAgendas: DEMO_PRODUCTION_AGENDAS,
  coilCuttingPlans: [],
  cargas: DEMO_CARGAS,
  expeditionRoutes: DEMO_EXPEDITION_ROUTES,
  productionSchedules: DEMO_SCHEDULES,
  extraHours: [],
  priceHistories: [],
  systemSettings: DEMO_SYSTEM_SETTINGS,
  agentReports: [],
  tornoEvents: [],
  machineStops: [],
  performanceQuestions: [],
  performanceReviews: [],
  attendances: [],
  laserQuotes: [],
  sheetStocks: [],
  sheetStockMovements: [],
  prensaPendingProductions: [],
};
